### PR TITLE
#167165028 Enable article share

### PR DESCRIPTION
**Pull request by ocranbillions**
#### What does this PR do?
- Implements the feature to share article

#### Description of Task to be completed?
- Install react-share
- Create article-share component
- Toggle display of social icons when the share button is clicked
- Share article when social Icon is clicked

#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
- [#167165028](https://www.pivotaltracker.com/story/show/167165028)

#### Screenshots (if appropriate)
Screenshot 2019-09-10 at 5 43 48 PM

Screenshot 2019-09-10 at 5 44 08 PM

### CODE REVIEW

**Comment by mazma1** [comment]
@ocranbillions this is what I have when I tried the facebook share:

Screenshot 2019-09-11 at 1 48 05 PM

What is "Nemo aut et odit."? I didn't write that.
Looks like it's sharing the base URL and not that of a specific article, is that the case?

UPDATE: I realised "Nemo aut et odit" is the article's title, what a strange title! Can you write a more custom message instead of sending only the article's title?

**Comment by mazma1** [comment]
Can the email share option open on a different tab instead of the current one?

**Comment by ocranbillions** [comment]
> @ocranbillions this is what I have when I tried the facebook share:
> 
> Screenshot 2019-09-11 at 1 48 05 PM
> 
> What is "Nemo aut et odit." I didn't write that?
> Looks like it's sharing the base URL and not that of a specific article, is that the case?

 "Nemo aut et odit' is the title of the article you're sharing. 
For facebook it looks like its the base url but when you share it, its the actual article link that gets shared.

**Comment by ocranbillions** [comment]
> Can the email share option open on a different tab instead of the current one?

On my system, it opens up a menu to choose which email client I would like to use. I doubt if I can have full control over that.

**Comment by mazma1** [comment]
> > Can the email share option open on a different tab instead of the current one?
> 
> On my system, it opens up a menu to choose which email client I would like to use. I doubt if I can have full control over that.

Mine just opens an email client on the same tab that has the article

**Comment by mazma1** [comment]
> > @ocranbillions this is what I have when I tried the facebook share:
> > Screenshot 2019-09-11 at 1 48 05 PM
> > What is "Nemo aut et odit." I didn't write that?
> > Looks like it's sharing the base URL and not that of a specific article, is that the case?
> 
> "Nemo aut et odit' is the title of the article you're sharing.
> For facebook it looks like its the base url but when you share it, its the actual article link that gets shared.

Did you see the part I said you should come up with a custom message instead of sharing only the article's title? Maybe include the author's name?

**Comment by ocranbillions** [comment]
> > > @ocranbillions this is what I have when I tried the facebook share:
> > > Screenshot 2019-09-11 at 1 48 05 PM
> > > What is "Nemo aut et odit." I didn't write that?
> > > Looks like it's sharing the base URL and not that of a specific article, is that the case?
> > 
> > 
> > "Nemo aut et odit' is the title of the article you're sharing.
> > For facebook it looks like its the base url but when you share it, its the actual article link that gets shared.
> 
> Did you see the part I said you should come up with a custom message instead of sharing only the article's title? Maybe include the author's name?

Ok. I'll work on that in a bit.

**Pull request merged**
